### ISSUE TITLE
no connection

### ISSUE THREAD

**Issue by hassan510-cmd** [haruncpi/barcode-server#3]
after first installed the mobile and jar file on the desktop, the program works perfectly, but when I try to use it again, it stuck in connect process and doesn't connect with my phone

https://user-images.githubusercontent.com/55447090/118124545-0577dc00-b3f6-11eb-8fbf-8181c7420f31.mp4

**Comment by haruncpi** [comment]
Try new [server app](https://github.com/haruncpi/barcode-server)
